// <auto-generated />
namespace CSharp_laba3._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NameMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202212071459013_NameMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
